name: Trigger auto deployment for container-app-w55sfykspbzfc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-w55sfykspbzfc-AutoDeployTrigger-57decf72-cf8e-4fec-8577-c26a1ecfa6e5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPW55SFYKSPBZFC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPW55SFYKSPBZFC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPW55SFYKSPBZFC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPW55SFYKSPBZFC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPW55SFYKSPBZFC_REGISTRY_PASSWORD }}
          containerAppName: container-app-w55sfykspbzfc
          resourceGroup: flaskbasic92d2a885
          imageToBuild: default/container-app-w55sfykspbzfc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


